version: "3.7"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    ports:
      - "5433:5432"
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      API_DATABASE_HOST: db
      API_DATABASE_PORT: 5432
      API_DATABASE_USER: postgres
      API_DATABASE_PASSWORD: postgres
      API_DATABASE_NAME: api
      API_DATABASE_LOG_LEVEL: debug
      MIGRATE: up
    command:
      ["dockerize", "-wait", "tcp://db:5432", "-timeout", "60s", "api", "serve"]

volumes:
  db_data:
